packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true

catalog:
  "@types/react": ^19.3.0
  "@types/react-dom": ^19.2.0
  react: ^19.3.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
