/**
 * Snapshots packages/content articles into src/generated/content.ts so `bun build --compile`
 * can embed every post and image into the binary.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, relative } from "node:path";
import { loadArticles } from "@portfolio/content/loader";

const drafts = process.argv.includes("--drafts");
const outFile = new URL("../src/generated/content.ts", import.meta.url).pathname;
const outDir = dirname(outFile);

const { articles, skipped } = loadArticles({ drafts });

const imports: string[] = [];
const imageIds = new Map<string, string>();

function importImage(path: string) {
  let id = imageIds.get(path);
  if (!id) {
    id = `image${imageIds.size}`;
    imageIds.set(path, id);
    imports.push(
      `import ${id} from ${JSON.stringify(relative(outDir, path))} with { type: "file" };`,
    );
  }
  return id;
}

const entries = articles.map((article) => {
  const images = Object.entries(article.images)
    .map(([src, path]) => `${JSON.stringify(src)}: ${importImage(path)}`)
    .join(", ");

  return `  {
    ...${JSON.stringify({ ...article.data, pubDate: article.data.pubDate.toISOString(), draft: article.draft })},
    body: ${JSON.stringify(article.body)},
    images: { ${images} },
  },`;
});

const source = `// Generated by scripts/generate-content.ts. Do not edit.
import type { EmbeddedArticle } from "../content/types.ts";
${imports.join("\n")}

export const articles: EmbeddedArticle[] = [
${entries.join("\n")}
];
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, source);

console.log(
  `content: ${articles.length} article(s)${drafts ? " including drafts" : ""}, ${imageIds.size} image(s)`,
);
for (const { file, reason } of skipped) console.log(`content: skipped ${file} (${reason})`);
